import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/shared/NavBar";
import Footer from "@/Components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* bg-zinc-950 ba bg-black ebong text-white use kora hoyeche dark look er jonne */}
      <body className="min-h-full flex flex-col bg-zinc-950 text-white">
        <Navbar></Navbar>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}